---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-app
spec:
  replicas: 1
  selector:
   matchLabels:
     name: auth-service-app
  template:
    metadata:
      labels:
        name: auth-service-app
    spec:
      containers:
        - name: application
          image: jbshaw/auth-service-latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              value: "8081"
